name: iOS Pull Request

on:
  pull_request:
    types: [ opened, reopened, synchronize, ready_for_review ]
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_test:
    name: Build and Test Package
    if: github.event.pull_request.draft == false
    runs-on: macos-14

    steps:
      - name: Run pull request workflow
        uses: govuk-one-login/mobile-ios-pipelines@5e5d61055acd97cfb4b22f53f6a51e70c7d778de
        with:
          action_type: 'Pull Request'
          package_scheme: Authentication-Package
          xcode_version: 15.2
          run_destination: platform=macOS,arch=arm64,variant=Mac Catalyst
          sonar_token: ${{ secrets.SONAR_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
